[[months]]
name = "january"
caption1 = "R • E • S • P • O • N • S • I • B • I • L • T • Y"
caption2 = "We Wouldn'tHave Gotten Hacked If They Had Only Listened to Us!"
colour = "#74C7EA"  # TODO: Fix colour

[[months]]
name = "january"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "february"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "march"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "april"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "may"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "june"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "july"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "august"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "september"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "october"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "november"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour

[[months]]
name = "december"
caption1 = "Caption 1 here"  # Fix caption 1
caption2 = "Caption 2 here"  # Fix caption 2
colour = "#FF0000"  # TODO: Fix colour
